<CalendarButton>:
    font_size: 32
    text: "Select date"
    size_hint_y: None
    size_hint_x: 5 * dp(48)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    opposite_colors: True


<SaveButton>:
    font_size: 32
    size_hint: None, None
    size: 6 * dp(48), dp(48)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    text: "Save"

<ProtectedButton>:
    size_hint_y: None
    size_hint_x: 5 * dp(48)
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    font_size: 32

